//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankTop
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TankTop.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes.
        /// </summary>
        public static string Indexes {
            get {
                return ResourceManager.GetString("Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}.
        /// </summary>
        public static string Indexes_Name {
            get {
                return ResourceManager.GetString("Indexes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/autocomplete.
        /// </summary>
        public static string Indexes_Name_AutoComplete {
            get {
                return ResourceManager.GetString("Indexes_Name_AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/docs.
        /// </summary>
        public static string Indexes_Name_Docs {
            get {
                return ResourceManager.GetString("Indexes_Name_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/docs/categories.
        /// </summary>
        public static string Indexes_Name_Docs_Categories {
            get {
                return ResourceManager.GetString("Indexes_Name_Docs_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/docs/variables.
        /// </summary>
        public static string Indexes_Name_Docs_Variables {
            get {
                return ResourceManager.GetString("Indexes_Name_Docs_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/functions.
        /// </summary>
        public static string Indexes_Name_Functions {
            get {
                return ResourceManager.GetString("Indexes_Name_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/functions/{1}.
        /// </summary>
        public static string Indexes_Name_Functions_Num {
            get {
                return ResourceManager.GetString("Indexes_Name_Functions_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/promote.
        /// </summary>
        public static string Indexes_Name_Promote {
            get {
                return ResourceManager.GetString("Indexes_Name_Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/indexes/{0}/search.
        /// </summary>
        public static string Indexes_Name_Search {
            get {
                return ResourceManager.GetString("Indexes_Name_Search", resourceCulture);
            }
        }
    }
}
